-- JType MySQL init script (docker-entrypoint-initdb.d)
-- This is used for fresh docker compose setups only.
-- The web service manages its own schema via migrations.rs
-- This file is kept minimal; the authoritative schema lives in
-- services/jtype-web/migrations/0001_init.up.sql
